export const FETCH_COINS = 'FETCH_COINS';
export const FETCH_COINS_SUCCESS = 'FETCH_COINS_SUCCESS';
export const FETCH_COIN_CHART = 'FETCH_COIN_CHART';
export const FETCH_COIN_CHART_SUCCESS = 'FETCH_COIN_CHART_SUCCESS';
export const FETCH_CURRENT_USER = 'FETCH_CURRENT_USER';